version: "2"

linters:
  settings:
    misspell:
      locale: US
 
    staticcheck:
      checks: ["all"]

  default: none
  enable:
    - misspell
    - staticcheck
    - govet
    - revive
    - ineffassign
    - unused
    - prealloc
    - unconvert

  exclusions:
    presets: []
    rules:
      - path: '(.+)\.go$'
        text: "ST1003.*don't use ALL_CAPS in Go names; use CamelCase"
      - path: '(.+)\.go$'
        text: "ST1000.*at least one file in a package should have a package comment"
      - path: '(.+)\.go$'
        text: "package-comments: should have a package comment"

formatters:
  enable:
    - goimports
    - gofumpt
